# Generated by Django 4.2.11 on 2026-07-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('job_status', 'Job Status'), ('dispute', 'Dispute'), ('chat', 'Chat'), ('system', 'System')], db_index=True, max_length=20),
        ),
    ]
