# Generated by Django 4.2.11 on 2026-07-21 11:44
# Data migration: backfill Review records from existing job ratings

from django.db import migrations


def backfill_reviews_from_jobs(apps, schema_editor):
    """Create Review records for all existing rated completed jobs."""
    Job = apps.get_model('bookings', 'Job')
    Review = apps.get_model('reviews', 'Review')

    for job in Job.objects.filter(
        status='COMPLETED',
        rating__isnull=False,
        artisan__isnull=False,
    ):
        Review.objects.get_or_create(
            customer_id=job.customer_id,
            artisan_id=job.artisan_id,
            defaults={
                'rating': job.rating,
                'comment': job.review or '',
                'job_id': job.id,
            },
        )

    # Recalculate all artisan ratings from the Review model
    from django.db.models import Avg, Count
    ArtisanProfile = apps.get_model('accounts', 'ArtisanProfile')
    for artisan in ArtisanProfile.objects.all():
        agg = Review.objects.filter(artisan=artisan).aggregate(
            avg_rating=Avg('rating'),
        )
        artisan.rating = round(agg['avg_rating'] or 0, 1)
        artisan.save(update_fields=['rating'])


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_reviews_from_jobs, migrations.RunPython.noop),
    ]