// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVjqtNFOHrEAXBC2z2Vo1wMCsCd5Ema_c',
    appId: '1:896772263250:web:02110d05151423a3ef7e8b',
    messagingSenderId: '896772263250',
    projectId: 'artisans-app-8a0d9',
    authDomain: 'artisans-app-8a0d9.firebaseapp.com',
    databaseURL: 'https://artisans-app-8a0d9-default-rtdb.firebaseio.com',
    storageBucket: 'artisans-app-8a0d9.firebasestorage.app',
    measurementId: 'G-82NER3ZG8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmQZhfVOL_DkMzqWCOEk1QDLV7wslZcQE',
    appId: '1:881602072860:android:6da31ff8e3146286fa6ad9',
    messagingSenderId: '881602072860',
    projectId: 'artisans-app-1b8ee',
    storageBucket: 'artisans-app-1b8ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgj4zqVzqFKq4VKeFCioaKZUwFlCw8B68',
    appId: '1:881602072860:ios:da5543cb0c1ddeadfa6ad9',
    messagingSenderId: '881602072860',
    projectId: 'artisans-app-1b8ee',
    storageBucket: 'artisans-app-1b8ee.firebasestorage.app',
    iosBundleId: 'com.example.artisansApp',
  );

}