# Generated by Django 5.2 on 2026-06-17 17:11

from django.db import migrations


def forwards(apps, schema_editor):
    """Seed the default commission rate setting."""
    AppSettings = apps.get_model('payments', 'AppSettings')
    AppSettings.objects.get_or_create(
        key='commission_rate',
        defaults={'value': '0.10'}
    )


def reverse(apps, schema_editor):
    """Remove the commission rate setting."""
    AppSettings = apps.get_model('payments', 'AppSettings')
    AppSettings.objects.filter(key='commission_rate').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]