# Generated by Django 4.2.11 on 2026-06-23 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_alter_transaction_created_at_alter_transaction_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(help_text="Paystack bank code (e.g., '058' for GTBank)", max_length=10)),
                ('account_number', models.CharField(max_length=10)),
                ('account_name', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the account has been verified via Paystack')),
                ('paystack_recipient_code', models.CharField(blank=True, help_text='Paystack transfer recipient code (set after verification)', max_length=100, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Primary account for withdrawals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER_OUT', 'Bank Transfer'), ('COMMISSION', 'Commission'), ('REFUND', 'Refund'), ('ESCROW_HOLD', 'Escrow Hold'), ('ESCROW_RELEASE', 'Escrow Release')], db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='wallet_balance_nonnegative'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('user', 'bank_code', 'account_number'), name='unique_user_bank_account'),
        ),
    ]
