# Generated by Django 4.2.11 on 2026-06-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_bankaccount_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer_code',
            field=models.CharField(blank=True, db_index=True, help_text='Paystack transfer code for tracking withdrawal status', max_length=100, null=True),
        ),
    ]
