# Generated by Django 4.2.11 on 2026-06-27 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_job_created_at_alter_job_status_and_more'),
        ('payments', '0007_add_transfer_code_to_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER_OUT', 'Bank Transfer'), ('COMMISSION', 'Commission'), ('REFUND', 'Refund'), ('ESCROW_HOLD', 'Escrow Hold'), ('ESCROW_RELEASE', 'Escrow Release'), ('PANDASCROW_FUND', 'Pandascrow Fund'), ('PANDASCROW_RELEASE', 'Pandascrow Release'), ('PANDASCROW_REFUND', 'Pandascrow Refund'), ('PANDASCROW_FEE', 'Pandascrow Fee')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='PandascrowEscrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_id', models.CharField(db_index=True, help_text='Pandascrow escrow identifier', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('INITIALIZED', 'Initialized'), ('FUNDED', 'Funded'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='INITIALIZED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Escrow amount in NGN', max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('pandascrow_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Fee charged by Pandascrow', max_digits=12, null=True)),
                ('partner_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Platform commission captured via partner_escrow_fee', max_digits=12, null=True)),
                ('inspection_period', models.IntegerField(default=3, help_text='Inspection period in days')),
                ('buyer_details', models.JSONField(blank=True, default=dict, help_text='Buyer details sent to Pandascrow')),
                ('seller_details', models.JSONField(blank=True, default=dict, help_text='Seller details sent to Pandascrow')),
                ('payment_url', models.URLField(blank=True, help_text='Pandascrow payment URL for customer to complete funding', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pandascrow_escrow', to='bookings.job')),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'status'], name='idx_pandascrow_job_status'), models.Index(fields=['escrow_id'], name='idx_pandascrow_escrow_id')],
            },
        ),
    ]
