# Generated by Django 5.2 on 2025-04-25 14:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='artisanprofile',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='artisanprofile',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='artisanprofile',
            name='price_range',
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='bank_account',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='bank_name',
            field=models.CharField(default='Bank name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='certificates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='jobs_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='location',
            field=models.CharField(default='artisan location', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='artisanprofile',
            name='verification_documents',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
