# Generated by Django 5.2 on 2025-04-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans_app', '0002_rename_verified_artisanprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtisanProfile',
        ),
    ]
