# Generated by Django 4.2.11 on 2026-06-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_artisanprofile_set_available_for_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='is_available',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('ENGAGED', 'Engaged'), ('OFFLINE', 'Offline')], default='OFFLINE', help_text="Artisan's current availability status", max_length=10),
        ),
    ]
