# Generated by Django 4.2.11 on 2026-06-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_artisanprofile_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='is_available',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('ENGAGED', 'Engaged'), ('OFFLINE', 'Offline')], db_index=True, default='OFFLINE', help_text="Artisan's current availability status", max_length=10),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='artisanprofile',
            name='profession',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='artisanprofile',
            index=models.Index(fields=['is_available', 'profession'], name='idx_artisan_avail_prof'),
        ),
    ]
