# Generated by Django 4.2.11 on 2026-07-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last time the user made an authenticated request. Used for online presence.', null=True),
        ),
    ]
