# Generated by Django 4.2.11 on 2026-06-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0002_alter_dispute_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status'], name='idx_dispute_status'),
        ),
    ]
