# Generated by Django 4.2.11 on 2026-06-26 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disputes', '0003_alter_dispute_created_at_alter_dispute_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Evidence file (image or document)', upload_to='dispute_evidence/%Y/%m/')),
                ('caption', models.CharField(blank=True, help_text='Optional description of the evidence', max_length=255)),
                ('file_type', models.CharField(blank=True, help_text='MIME type of the uploaded file', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='disputes.dispute')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence File',
                'verbose_name_plural': 'Evidence Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
