# Generated by Django 4.2.11 on 2026-07-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0004_add_evidence_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='resolution_amount',
        ),
    ]
