# Generated by Django 4.2.11 on 2026-06-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_alter_chat_options_remove_chat_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='audio_duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chat_audio/'),
        ),
        migrations.AddField(
            model_name='chat',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice_note', 'Voice Note')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
