# Generated by Django 4.2.11 on 2026-06-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chat_audio_duration_chat_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='location_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chat',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('voice_note', 'Voice Note'), ('location', 'Location')], default='text', max_length=20),
        ),
    ]
