# Generated by Django 4.2.11 on 2026-06-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chat_latitude_chat_location_label_chat_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.conversation'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['conversation', 'is_read'], name='idx_chat_conv_read'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['conversation', 'timestamp'], name='idx_chat_conv_timestamp'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client', 'is_active'], name='idx_conv_client_active'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['artisan', 'is_active'], name='idx_conv_artisan_active'),
        ),
    ]
