# Generated by Django 4.2.11 on 2026-07-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_chat_conversation_alter_chat_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='message_ttl_days',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Never expire'), (7, '1 week'), (14, '2 weeks'), (30, '1 month')], default=14, help_text='Days to retain messages. 0 = never auto-delete.'),
        ),
    ]
