# Generated by Django 5.2 on 2026-06-17 17:11

from django.db import migrations


def forwards(apps, schema_editor):
    """Convert existing SCHEDULED jobs to PENDING status."""
    Job = apps.get_model('bookings', 'Job')
    # The model field now uses PENDING as default, but old data may have SCHEDULED
    Job.objects.filter(status='SCHEDULED').update(status='PENDING')


def reverse(apps, schema_editor):
    """Reverse: convert PENDING back to SCHEDULED."""
    Job = apps.get_model('bookings', 'Job')
    Job.objects.filter(status='PENDING').update(status='SCHEDULED')


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_job_admin_approved_at_job_admin_approved_by_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]