# Generated by Django 4.2.11 on 2026-06-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ADMIN_APPROVED', 'Admin Approved'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('AWAITING_REVIEW', 'Awaiting Review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DISPUTED', 'Disputed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['customer', 'status'], name='idx_job_customer_status'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['artisan', 'status'], name='idx_job_artisan_status'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='idx_job_status'),
        ),
    ]
