# Generated by Django 4.2.11 on 2026-07-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_job_created_at_alter_job_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='escrow_held_amount',
        ),
    ]
