# Generated by Django 4.2.11 on 2026-07-23 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('PREMIUM', 'Premium')], db_index=True, default='FREE', help_text='Current subscription tier.', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the current tier expires. Null means no expiry (Free tier).', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes (payment reference, bank transfer details, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, help_text='Admin who activated this tier.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('artisan', models.OneToOneField(help_text='The artisan this subscription belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.artisanprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['tier', 'expires_at'], name='idx_sub_tier_expires')],
            },
        ),
    ]
