from django.urls import path
from .views import (
    UserRegistrationAPIView,
    UserLoginAPIView,
    CurrentUserAPIView,
    ChangePasswordView,
    LogoutView,
    ArtisanAvailabilityToggleView,
    ArtisanProfileSelfUpdateView,
    CustomerProfileSelfUpdateView,
    UserActivateAPIView,
    CustomerListAPIView,
    ArtisanLocationUpdateView,
    ProfilePictureUploadView,
    ForgotPasswordView,
    ResetPasswordView,
    VerificationDocumentUploadView,
    VerificationDocumentDeleteView,
    UserOnlineStatusView,
    EmailVerifyView,
    ResendEmailVerifyView,
)
app_name = 'accounts'

urlpatterns = [
    path('register/', UserRegistrationAPIView.as_view(), name='user-register'),
    path('login/', UserLoginAPIView.as_view(), name='user-login'),
    path('logout/', LogoutView.as_view(), name='user-logout'),
    path('me/', CurrentUserAPIView.as_view(), name='current-user'),
    path('me/upload-picture/', ProfilePictureUploadView.as_view(), name='upload-profile-picture'),
    path('me/artisan-profile/', ArtisanProfileSelfUpdateView.as_view(), name='artisan-self-profile'),
    path('me/customer-profile/', CustomerProfileSelfUpdateView.as_view(), name='customer-self-profile'),
    path('me/availability/', ArtisanAvailabilityToggleView.as_view(), name='artisan-availability'),
    path('me/update-location/', ArtisanLocationUpdateView.as_view(), name='artisan-location-update'),
    path('me/verification-documents/', VerificationDocumentUploadView.as_view(), name='verification-documents'),
    path('me/verification-documents/<int:index>/', VerificationDocumentDeleteView.as_view(), name='verification-document-delete'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('verify-email/', EmailVerifyView.as_view(), name='verify-email'),
    path('resend-verify-email/', ResendEmailVerifyView.as_view(), name='resend-verify-email'),
    path('users/<int:pk>/activate/', UserActivateAPIView.as_view(), name='user-activate'),
    path('users/<int:user_id>/online/', UserOnlineStatusView.as_view(), name='user-online-status'),
    path('customers/', CustomerListAPIView.as_view(), name='customer-list'),
]